steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sed -i '/GOOGLE_APPLICATION_CREDENTIALS/d' Dockerfile
    #args:
    #  - '-c'
    #  - |
    #    grep "GOOGLE_APPLICATION_CREDENTIALS" Dockerfile
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - '--build-arg'
      - 'EPA_TOKEN=$_EPA_TOKEN'
      - '--build-arg'
      - 'CWB_TOKEN=$_CWB_TOKEN'
      - '--build-arg'
      - 'ACCESS_TOKEN=$_ACCESS_TOKEN'
      - '--build-arg'
      - 'SECRET=$_SECRET'
      - '--build-arg'
      - 'OPENAI_TOKEN=$_OPENAI_TOKEN'
      - '--build-arg'
      - 'LOG_PATH=$_LOG_PATH'
      - '-f'
      - Dockerfile
      - .      
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=${_LOCATION}-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _PLATFORM: managed
  _SERVICE_NAME: line-bot
  _DEPLOY_REGION: asia-east1
  _GCR_HOSTNAME: asia.gcr.io
  _LABELS: gcb-trigger-id=348065bc-d8b3-43d6-961c-b5f2b34eedf7
  _TRIGGER_ID: 348065bc-d8b3-43d6-961c-b5f2b34eedf7
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - line-bot